extends SceneTree

func _initialize() -> void:
    _check.call_deferred()

func _check() -> void:
    var book := SpatialBook.new()
    root.add_child(book)
    await process_frame
    var image := Image.create(16, 16, false, Image.FORMAT_RGB8)
    image.fill(Color.WHITE)
    var texture := ImageTexture.create_from_image(image)
    book.set_chapter(5)
    assert(not book.begin_turn(-1), "First spread cannot turn backward")
    assert(not book.begin_turn(1), "Unloaded target spread cannot turn")
    for index in range(5):
        book.supply_page(index, texture)
    assert(book.begin_turn(1))
    book.set_turn_progress(0.25)
    book.release_turn()
    await create_timer(0.35).timeout
    assert(book.first_page == 0, "Cancelled grab must not change reading position")
    assert(book.step(1))
    await create_timer(0.35).timeout
    assert(book.first_page == 2)
    assert(book.step(1))
    await create_timer(0.35).timeout
    assert(book.first_page == 4, "Odd final page is a valid spread")
    assert(not book.step(1))
    assert(book.seek(1))
    assert(book.first_page == 0)
    book.rtl = true
    assert(book.begin_turn(-1), "RTL next turn starts on the left")
    book.set_turn_progress(0.75)
    book.release_turn()
    await create_timer(0.35).timeout
    assert(book.first_page == 2)
    assert(book.begin_turn(1))
    book.cancel_turn()
    assert(book.first_page == 2, "Tracking loss must cancel without changing position")
    assert(book.turn_direction == 0)
    assert(not book.turning_leaf.visible)
    book.set_chapter(100)
    book.prepare_seek(80)
    book.supply_page(80, texture)
    assert(not book.seek(80), "Seek waits for both pages")
    book.supply_page(81, texture)
    assert(book.seek(80), "Far seek pages must survive cache trimming")
    assert(book.first_page == 80)
    # A tall source page switches to the large scroll window and keeps its
    # original aspect ratio instead of being forced into a spread.
    book.set_mode("auto")
    book.set_chapter(2)
    var tall := Image.create(100, 500, false, Image.FORMAT_RGB8)
    tall.fill(Color.WHITE)
    var tall_texture := ImageTexture.create_from_image(tall)
    book.supply_page(0, tall_texture, Vector2i(100, 500))
    assert(book.scroll_mode, "Tall pages select scroll-window mode automatically")
    assert(book.scroll_by(0.20) == 0)
    assert(book.scroll_offset > 0.0, "Scroll drag advances the long page")
    book.set_mode("book")
    assert(not book.scroll_mode, "Reader settings can force two-page mode")
    book.set_open(0.0)
    var contact := Vector3(0.25, -0.18, 0.025)
    book.begin_cover(contact)
    book.drag_cover(contact)
    assert(is_zero_approx(book.openness), "Cover acquisition cannot jump the hinge")
    book.drag_cover(Vector3(0.0, -0.18, 0.25))
    assert(book.openness > 0.4, "Captured cover follows hand motion")
    book.cancel_turn()
    assert(not book.cover_dragged and is_zero_approx(book.openness), "Tracking loss restores the cover acquisition state")
    book.begin_cover(contact)
    book.set_open(0.8)
    book.release_cover()
    await create_timer(0.3).timeout
    assert(is_equal_approx(book.openness, 1.0), "Cover release settles open")
    book.set_chapter(4)
    for index in range(4):
        book.supply_page(index, texture)
    assert(book.begin_turn(1, contact))
    book.drag(contact)
    assert(is_zero_approx(book.turn_progress), "Page acquisition starts at the contact without jumping")
    book.drag(Vector3(-0.1, -0.18, 0.2))
    assert(book.turn_progress > 0.5, "Crossing the spine advances the grabbed leaf")
    book.drag(contact)
    assert(is_zero_approx(book.turn_progress), "Physical page drag reverses immediately")
    book.cancel_turn()
    book.set_chapter(20, 14)
    book.supply_page(14, texture)
    book.supply_page(15, texture)
    book.supply_page(0, texture)
    assert(book.cover_texture == texture, "Resumed cover survives current-spread cache trimming")
    assert(book.right_leaf.material_override.get_shader_parameter("front_image") == texture, "Resumed spread receives decoded images")
    assert(book.right_leaf.mesh.surface_get_array_len(0) == 64 * 24 * 6, "Turning leaves retain the denser curved surface")
    book.set_open(0)
    assert(book.cover_face.global_position.z > book.body_parts[3].global_position.z, "Closed cover art stays in front of the flattened page block")
    book.queue_free()
    print("PASS: book loading, boundaries, seek, RTL, grab cancellation and settlement")
    quit()
